### ISSUE TITLE
Status messages styling broken with big pipe after 10.3 drupal core update

### ISSUE THREAD

**Issue by vever001** [openeuropa/oe_bootstrap_theme#419]
This is a preliminary report (will update once/if we start working on this).

After updating to drupal core 10.3, if the website uses big_pipe, it seems status messages are no longer styled (bypassing status-messages.html.twig) and show up unstyled/raw.
This seems to come from https://www.drupal.org/project/drupal/issues/3379885 which already has some reports of similar cases. 

This may require implementing `Drupal.theme.message` as per https://www.drupal.org/project/drupal/issues/3456176#comment-15692107

**Comment by drishu** [comment]
needs more info, like steps to reproduce including what is expected versus what is actually.

**Comment by vever001** [comment]
This is very easy to reproduce:
 - Install clean drupal core 10.2.x (standard profile*), oe_bootstrap_theme + helper, set theme as default
 - Login as superadmin, add a new page, notice the status message is OK/styled
![image](https://github.com/user-attachments/assets/4f3b5595-8286-49f5-85cf-cc4ecfb373a1)
- Now update to 10.3.x, create or update a basic page, notice status messages are unstyled, broken
![image](https://github.com/user-attachments/assets/ba3c239b-2e01-4fbf-a7a4-31d9554157d7)


[3379885](https://www.drupal.org/project/drupal/issues/3379885) was introduced in 10.3.0
*Big pipe comes enabled by default with the standard profile

**Comment by enriquelacoma** [comment]
The issue was fixed in https://www.drupal.org/project/drupal/issues/3379885

**Comment by vever001** [comment]
> The issue was fixed in https://www.drupal.org/project/drupal/issues/3379885

No, this is still relevant. Please reopen the issue.
I just reproduced this now with the oe_bootstrap_theme docker install and using the standard profile.
As stated, https://www.drupal.org/project/drupal/issues/3379885 is the issue that introduced the regression, on 10.3.0, which happens when bigpipe is enabled. 

See also https://www.drupal.org/project/drupal/issues/3457518 and https://www.drupal.org/project/drupal/issues/3396318
For now, since #3396318 is still ongoing, the only fix is to override  `Drupal.theme.message`, like many other themes did.

**Comment by vever001** [comment]
cc @enriquelacoma @drishu
Thank you

**Comment by vever001** [comment]
Could we please reopen? I do not have permissions. This issue is still valid.
FWIW I left a review in the opened PR. We can improve it further.
I'm not sure who to ping cc @enriquelacoma @drishu @tibi2303
Thank you
